import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import AllAppProviders from '@/providers/AllAppProviders'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AllAppProviders>
        <Header />
        <body className={inter.className}>{children}</body>
      </AllAppProviders>
    </html>
  )
}
