import { TableDash } from "@/components/dashboardSide/TableDash";

export default function Sections() {
  const header = [
    "ID",
    "Text",
    "Title",
    "Subtitle",
    "Img",
    "Type",
    "User",
    "Hidden",
  ];
  const rows = [
    {
      id: "1",
      text: "text1",
      title: "title1",
      subtitle: "subtitle1",
      img: "imgref1",
      type: "Hej1",
      user: "User1",
      isVisible: true,
    },
    {
      id: "2",
      text: "text2",
      title: "title2",
      subtitle: "subtitle2",
      img: "imgref2",
      type: "Hej2",
      user: "User2",
      isVisible: true,
    },
    {
      id: "3",
      text: "text3",
      title: "title3",
      subtitle: "subtitle3",
      img: "imgref3",
      type: "Hej3",
      user: "User3",
      isVisible: false,
    },
    {
      id: "4",
      text: "text4",
      title: "title4",
      subtitle: "subtitle4",
      img: "imgref4",
      type: "Hej4",
      user: "User4",
      isVisible: true,
    },
    {
      id: "44",
      text: "text4",
      title: "title4",
      subtitle: "subtitle4",
      img: "imgref4",
      type: "Hej4",
      user: "User5",
      isVisible: true,
    },
    {
      id: "5",
      text: "text5",
      title: "title5",
      subtitle: "subtitle5",
      img: "imgref5",
      type: "Hej5",
      user: "User6",
      isVisible: false,
    },
    {
      id: "6",
      text: "text6",
      title: "title6",
      subtitle: "subtitle6",
      img: "imgref6",
      type: "Hej6",
      user: "User7",
      isVisible: true,
    },
    {
      id: "7",
      text: "text7",
      title: "title7",
      subtitle: "subtitle7",
      img: "imgref7",
      type: "Hej7",
      user: "User8",
      isVisible: true,
    },
    {
      id: "8",
      text: "text8",
      title: "title8",
      subtitle: "subtitle8",
      img: "imgref8",
      type: "Hej8",
      user: "User9",
      isVisible: false,
    },
  ];
  return <TableDash header={header} rows={rows} form="Sections" />;
}
